name: Publish Prod Config Updates
on:
    push:
        branches: 
            - main
        paths:
            - '**.prod.config.json'
jobs:
    get-secrets:
        runs-on: ubuntu-latest
        steps:
            - name: Load secret
              uses: 1password/load-secrets-action@v1
              with:
              # Export loaded secrets as environment variables
                export-env: true
              env:
                OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
                SECRET: op://hello-world/secret/credential

    publish-configs:
        permissions:
            contents: write
            pull-requests: write
            checks: write
            actions: read
            id-token: write
            packages: write
        uses: ./.github/workflows/publish-configs-1pass.yml
        secrets: 
            MY-SECRET: $SECRET
            SECRET1: $SECRET
        with:
            publish-url: 'https://webhook.site/c33c6f62-9347-46d2-8e88-218eeeee7464'

